### ISSUE TITLE
Loading wrong iwad

### ISSUE THREAD

**Issue by SirKnightTG** [sultim-t/prboom-plus-rt#48]
When I first was trying this build, I mistakenly dropped the files into my Doom 2 folder, which is not supported yet. First running a launcher popped up where I selected the doom2 iwad.

But now I dropped the files from the zip into my Ultimate Doom folder and when I run it, I no longer get the launcher and I get an error about an unsupported wad. When starting a new game, instead of seeing Doom 1 E1M1, it loads map 01 from Doom 2. WTF?

So is this prboom port writing a cfg file somewhere that's not in the same location as the exe? I know it generates a cfg there but that has nothing to do with this issue.

**Comment by NO0bMaster69** [comment]
As far as I know, prboom-plus only writes the config file to the folder that the exe is in. If you have both the WAD files of DOOM and DOOM2 in the folder, it will default to DOOM2.WAD so that could be your issue - if that's the case, simply delete/move DOOM2.WAD. If that's not your issue, I suggest unzipping this port into its own folder rather than your Ultimate Doom folder and then copying DOOM.WAD to it. If you purchased doom through steam, this will be the wad that is located under `Steam\steamapps\common\Ultimate Doom\base`

**Comment by SirKnightTG** [comment]
Making a new folder with prboom-plus-rt and the doom.wad did not help. It still loads my Doom 2 wad.

There has to be some config being written somewhere system wide from that one and only time the launcher loaded. I checked the Saved Games folder under the Users folder for my username but there's nothing about doom there. Maybe I'll just need to look into the source code more closely. This is very odd.

**Comment by NO0bMaster69** [comment]
If you pause the game and go to Options > Prboom > General > Right Arrow, what do you see under the "Files preloaded at game startup" section? If your game is loading a config from a file other than the one in the game directory, you should be able to modify it by changing these values.

**Comment by sultim-t** [comment]
PrBoom tries to find standard .wad files in these directories: https://github.com/sultim-t/prboom-plus-rt/blob/1449cd400ca8e7514baed8f58e19339d315dfb4a/prboom2/src/SDL/i_system.c#L428
Maybe `doom2.wad` is in one of them.
Anyway, it's possible to just pass `-iwad doom` argument to `.exe`
