### ISSUE TITLE
Linux binaries?

### ISSUE THREAD

**Issue by databoose** [sultim-t/prboom-plus-rt#69]
I was curious if linux binaries will ever come out for the releases, or if it's not happening,thanks.

**Comment by davefletcher1983** [comment]
From the readme it says to install through package manager. So it seems it builds it for you.

**Comment by PoorPocketsMcNewHold** [comment]
> From the readme it says to install through package manager. So it seems it builds it for you.

Not automatically. This is referring to the build instructions, as instead of Windows, you don't have to download external dependencies from a provided .zip file.

However, Compilling it is not really something that all Linux user are skilled at, atleast, not a small part of it. Hence, building Linux builds as well could be of a great help to just, pick up and go as most Windows user as well.

**Comment by mhalano** [comment]
Could we have a list of packages necessary to compile in multiple Linux distros? By multiple, I mean Debian/Ubuntu and Red Hat like distros

**Comment by PoorPocketsMcNewHold** [comment]
> Could we have a list of packages necessary to compile in multiple Linux distros? By multiple, I mean Debian/Ubuntu and Red Hat like distros

https://github.com/sultim-t/prboom-plus-rt/blob/master/prboom2/INSTALL

Keep general Linux compilling discussion to #39 i guess
