### ISSUE TITLE
Possible future suport for older GPU`s? GTX 980?

### ISSUE THREAD

**Issue by 3m2oo5** [sultim-t/prboom-plus-rt#70]
As in title..

As a owner of wonderful ROG G751 with Maxwell gtx  980m i was wondering will there be ever possible to run that piece of code..

Can you clarify once and definly?

Take care, great job !

**Comment by NO0bMaster69** [comment]
Sadly this isn't possible because older gpus like the gtx 980 don't have driver support for the VK_KHR_ray_tracing_pipeline extension that this mod uses.  The list on [gpuinfo](https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_ray_tracing_pipeline&platform=alll) has all of the gpus that report driver support for VK_KHR_raytracing_pipeline and out of these some older ones including gtx 1000 series don't have full driver support and aren't capable of running the mod.

**Comment by 3m2oo5** [comment]
Clear answer. Thanks

And - amazing job with that mod :)

**Comment by Calinou** [comment]
> Sadly this isn't possible because older gpus like the gtx 980 don't have driver support for the VK_KHR_ray_tracing_pipeline extension that this mod uses. The list on [gpuinfo](https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_ray_tracing_pipeline&platform=alll) has all of the gpus that report driver support for VK_KHR_raytracing_pipeline and out of these some older ones including gtx 1000 series don't have full driver support and aren't capable of running the mod.

It is possible to run some kind of fallback (at least on Pascal GPUs), but it needs to be implemented on a per-application basis in Vulkan. Unlike Direct3D 12, there is no driver-level fallback provided. This is how Quake 2 RTX can run on non-RTX GPUs despite its name :slightly_smiling_face: (slowly, but playable at low settings on GTX 1080/1080 Ti)

**Edit:** For those looking to run PrBoom+ RT on a non-raytracing-capable GPU, download the 1.0.7 prerelease and replace RaytracedGL1.dll with the one linked here: https://github.com/sultim-t/prboom-plus-rt/issues/12#issuecomment-1113762046

It will be slow as emulating raytracing functionality using compute shaders is much slower than using dedicated RT units. Stick to a low resolution (ideally 4:3) and consider leaving the framerate cap to the vanilla 35 FPS.
